function(add_simd_flags target extension)
    if(MSVC)
        # SSE2 is default in MSVC and it doesn't require any compilation option

        if(extension STREQUAL "SSE3" OR extension STREQUAL "SSSE3" OR extension STREQUAL "SSE4.1")
            message(WARNING "There is no option for ${extension} in MSVC. Falling back to SSE2.")
        elseif(extension STREQUAL "SSE4.2")
            target_compile_options(${target} PRIVATE /d2archSSE42)  # hidden msvc option
        elseif(extension STREQUAL "AVX")
            target_compile_options(${target} PRIVATE /arch:AVX)
        elseif(extension STREQUAL "AVX2")
            target_compile_options(${target} PRIVATE /arch:AVX2)
        elseif(extension STREQUAL "AVX512")
            target_compile_options(${target} PRIVATE /arch:AVX512)
        elseif(extension STREQUAL "NATIVE")
            message(WARNING "There is no option for native architecture in MSVC. Using SSE2.")
        endif()
    else()
        if(extension STREQUAL "SSE2")
            target_compile_options(${target} PRIVATE -msse2)
        elseif(extension STREQUAL "SSE3")
            target_compile_options(${target} PRIVATE -msse3)
        elseif(extension STREQUAL "SSSE3")
            target_compile_options(${target} PRIVATE -mssse3)
        elseif(extension STREQUAL "SSE4.1")
            target_compile_options(${target} PRIVATE -msse4.1)
        elseif(extension STREQUAL "SSE4.2")
            target_compile_options(${target} PRIVATE -msse4.2)
        elseif(extension STREQUAL "AVX")
            target_compile_options(${target} PRIVATE -mavx)
        elseif(extension STREQUAL "AVX2")
            target_compile_options(${target} PRIVATE -mavx2)
        elseif(extension STREQUAL "AVX512")
            target_compile_options(${target} PRIVATE -mavx512f)
        elseif(extension STREQUAL "NATIVE")
            target_compile_options(${target} PRIVATE -march=native)
        endif()
    endif()
endfunction()
