name: sphinx-build

on:
  push:
    branches: [ master ]

env:
  BUILD_TYPE: Release
  GITHUB_ACTOR: DataMedSci
  GITHUB_REPOSITORY: DataMedSci/gi-yagit


jobs:

  build_sphinx_job:
    runs-on: ubuntu-latest
    container: debian:stable-slim

    steps:

      - name: Get prerequisites
        run: |
          apt-get update
          apt-get install -y git python3-pip doxygen
        shell: bash

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run doxygen and prepare for Sphinx
        run: |
          rm -f .gitignore
          cd docs/
          mkdir build
          cd source/
          doxygen
          cd ../
        shell: bash

      - name: Build and Commit
        uses: sphinx-notes/pages@2.0
        with:
          documentation_path: docs/source
          requirements_path: docs/requirements.txt

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
